sudo: false
language: go

os:
  - linux
  - osx

go:
  - 1.11.x
  - 1.12.x
  - master

env:
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: master
  fast_finish: true

cache:
  directories:
    - $HOME/.cache/go-build
