version: "{build}"

os: unstable

clone_folder: c:\gopath\src\github.com\tormoder\fit

environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build_script:
   - C:\MinGW\msys\1.0\bin\sh --login -c "
       make
       "
