ignored = [
  # Assume that 'github.com/tormoder/fit' is available,
  # since 'cmd/fitgen' is a part of this repository.
  "github.com/tormoder/fit/internal/types"
]

[[constraint]]
  # For tests in 'cmd/fitgen/internal/profile'.
  name = "github.com/cespare/xxhash"
  version = "1.0.0"

[[constraint]]
  # For 'cmd/fitgen'.
  name = "github.com/tealeg/xlsx"
  version = "1.0.3"
